import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ЗГУ > БГУ",
  description: "Generated by Nurik",
  icons: {
    icon: "/favicon.ico", // опционально
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body>{children}</body>
    </html>
  );
}
